schema_version: 1

context:
  version: "3.0.11"

package:
  name: djhtml
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/d/djhtml/djhtml-${{ version }}.tar.gz
  sha256: dbaf55684294bda6486a094954e43847a1c0945e521282e008a9aabdac245688

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - djtxt = djhtml.__main__:main
      - djhtml = djhtml.__main__:main
      - djcss = djhtml.__main__:main
      - djjs = djhtml.__main__:main

requirements:
  host:
    - pip
    - python =${{ python_min }}
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - djhtml
  - requirements:
      run:
        - pip
        - python =${{ python_min }}
    script:
      - pip check
      - djtxt --help
      - djhtml --help
      - djcss --help
      - djjs --help

about:
  summary: Django/Jinja template indenter
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/rtts/djhtml

extra:
  recipe-maintainers:
    - danielnachun
